// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/database/batting_stats.dart';
import 'src/database/bowling_stats.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6877489737263573673),
    name: 'BattingStats',
    lastPropertyId: const obx_int.IdUid(11, 1467976945630097273),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5102488118071254901),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9197799658361074978),
        name: 'batID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6932059736824306028),
        name: 'inningsType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2042546768178606896),
        name: 'teamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6392699258919080936),
        name: 'playerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9064547190407760190),
        name: 'runs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6906451465969281540),
        name: 'ballsPlayed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6988015229037000492),
        name: 'fours',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7073053892015011870),
        name: 'sixes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6208351790221096772),
        name: 'dotBalls',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1467976945630097273),
        name: 'strikeRate',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3552183586018785394),
    name: 'BowlingStats',
    lastPropertyId: const obx_int.IdUid(11, 3012067541960380773),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3656948228772132877),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 366759854926635409),
        name: 'bowlID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6316401887683217313),
        name: 'inningsType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 62528939362929624),
        name: 'teamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3815260666571265413),
        name: 'playerId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5990287459761714060),
        name: 'oversBowled',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1069581937176268449),
        name: 'runsGiven',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6715775437910844696),
        name: 'wicketsConceded',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2504546502487939545),
        name: 'extras',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8047213814270774846),
        name: 'maidens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3012067541960380773),
        name: 'economyRate',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 3552183586018785394),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BattingStats: obx_int.EntityDefinition<BattingStats>(
      model: _entities[0],
      toOneRelations: (BattingStats object) => [],
      toManyRelations: (BattingStats object) => {},
      getId: (BattingStats object) => object.id,
      setId: (BattingStats object, int id) {
        object.id = id;
      },
      objectToFB: (BattingStats object, fb.Builder fbb) {
        final batIDOffset = fbb.writeString(object.batID);
        final inningsTypeOffset = fbb.writeString(object.inningsType);
        final teamIdOffset = fbb.writeString(object.teamId);
        final playerIdOffset = fbb.writeString(object.playerId);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, batIDOffset);
        fbb.addOffset(2, inningsTypeOffset);
        fbb.addOffset(3, teamIdOffset);
        fbb.addOffset(4, playerIdOffset);
        fbb.addInt64(5, object.runs);
        fbb.addInt64(6, object.ballsPlayed);
        fbb.addInt64(7, object.fours);
        fbb.addInt64(8, object.sixes);
        fbb.addInt64(9, object.dotBalls);
        fbb.addFloat64(10, object.strikeRate);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final batIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final inningsTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final runsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final ballsPlayedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final foursParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final sixesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final dotBallsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final strikeRateParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = BattingStats(
          batID: batIDParam,
          inningsType: inningsTypeParam,
          teamId: teamIdParam,
          playerId: playerIdParam,
          runs: runsParam,
          ballsPlayed: ballsPlayedParam,
          fours: foursParam,
          sixes: sixesParam,
          dotBalls: dotBallsParam,
          strikeRate: strikeRateParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    BowlingStats: obx_int.EntityDefinition<BowlingStats>(
      model: _entities[1],
      toOneRelations: (BowlingStats object) => [],
      toManyRelations: (BowlingStats object) => {},
      getId: (BowlingStats object) => object.id,
      setId: (BowlingStats object, int id) {
        object.id = id;
      },
      objectToFB: (BowlingStats object, fb.Builder fbb) {
        final bowlIDOffset = fbb.writeString(object.bowlID);
        final inningsTypeOffset = fbb.writeString(object.inningsType);
        final teamIdOffset = fbb.writeString(object.teamId);
        final playerIdOffset = fbb.writeString(object.playerId);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, bowlIDOffset);
        fbb.addOffset(2, inningsTypeOffset);
        fbb.addOffset(3, teamIdOffset);
        fbb.addOffset(4, playerIdOffset);
        fbb.addFloat64(5, object.oversBowled);
        fbb.addInt64(6, object.runsGiven);
        fbb.addInt64(7, object.wicketsConceded);
        fbb.addInt64(8, object.extras);
        fbb.addInt64(9, object.maidens);
        fbb.addFloat64(10, object.economyRate);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final bowlIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final inningsTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final playerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final oversBowledParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final runsGivenParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final wicketsConcededParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final extrasParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final maidensParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final economyRateParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = BowlingStats(
          bowlID: bowlIDParam,
          inningsType: inningsTypeParam,
          teamId: teamIdParam,
          playerId: playerIdParam,
          oversBowled: oversBowledParam,
          runsGiven: runsGivenParam,
          wicketsConceded: wicketsConcededParam,
          extras: extrasParam,
          maidens: maidensParam,
          economyRate: economyRateParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BattingStats] entity fields to define ObjectBox queries.
class BattingStats_ {
  /// See [BattingStats.id].
  static final id = obx.QueryIntegerProperty<BattingStats>(
    _entities[0].properties[0],
  );

  /// See [BattingStats.batID].
  static final batID = obx.QueryStringProperty<BattingStats>(
    _entities[0].properties[1],
  );

  /// See [BattingStats.inningsType].
  static final inningsType = obx.QueryStringProperty<BattingStats>(
    _entities[0].properties[2],
  );

  /// See [BattingStats.teamId].
  static final teamId = obx.QueryStringProperty<BattingStats>(
    _entities[0].properties[3],
  );

  /// See [BattingStats.playerId].
  static final playerId = obx.QueryStringProperty<BattingStats>(
    _entities[0].properties[4],
  );

  /// See [BattingStats.runs].
  static final runs = obx.QueryIntegerProperty<BattingStats>(
    _entities[0].properties[5],
  );

  /// See [BattingStats.ballsPlayed].
  static final ballsPlayed = obx.QueryIntegerProperty<BattingStats>(
    _entities[0].properties[6],
  );

  /// See [BattingStats.fours].
  static final fours = obx.QueryIntegerProperty<BattingStats>(
    _entities[0].properties[7],
  );

  /// See [BattingStats.sixes].
  static final sixes = obx.QueryIntegerProperty<BattingStats>(
    _entities[0].properties[8],
  );

  /// See [BattingStats.dotBalls].
  static final dotBalls = obx.QueryIntegerProperty<BattingStats>(
    _entities[0].properties[9],
  );

  /// See [BattingStats.strikeRate].
  static final strikeRate = obx.QueryDoubleProperty<BattingStats>(
    _entities[0].properties[10],
  );
}

/// [BowlingStats] entity fields to define ObjectBox queries.
class BowlingStats_ {
  /// See [BowlingStats.id].
  static final id = obx.QueryIntegerProperty<BowlingStats>(
    _entities[1].properties[0],
  );

  /// See [BowlingStats.bowlID].
  static final bowlID = obx.QueryStringProperty<BowlingStats>(
    _entities[1].properties[1],
  );

  /// See [BowlingStats.inningsType].
  static final inningsType = obx.QueryStringProperty<BowlingStats>(
    _entities[1].properties[2],
  );

  /// See [BowlingStats.teamId].
  static final teamId = obx.QueryStringProperty<BowlingStats>(
    _entities[1].properties[3],
  );

  /// See [BowlingStats.playerId].
  static final playerId = obx.QueryStringProperty<BowlingStats>(
    _entities[1].properties[4],
  );

  /// See [BowlingStats.oversBowled].
  static final oversBowled = obx.QueryDoubleProperty<BowlingStats>(
    _entities[1].properties[5],
  );

  /// See [BowlingStats.runsGiven].
  static final runsGiven = obx.QueryIntegerProperty<BowlingStats>(
    _entities[1].properties[6],
  );

  /// See [BowlingStats.wicketsConceded].
  static final wicketsConceded = obx.QueryIntegerProperty<BowlingStats>(
    _entities[1].properties[7],
  );

  /// See [BowlingStats.extras].
  static final extras = obx.QueryIntegerProperty<BowlingStats>(
    _entities[1].properties[8],
  );

  /// See [BowlingStats.maidens].
  static final maidens = obx.QueryIntegerProperty<BowlingStats>(
    _entities[1].properties[9],
  );

  /// See [BowlingStats.economyRate].
  static final economyRate = obx.QueryDoubleProperty<BowlingStats>(
    _entities[1].properties[10],
  );
}
